version: '3.8'

services:
  redpanda-broker:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    ports: 
      - "19092:19092"
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda-broker:9092,external://localhost:19092
    volumes:
      - redpanda_data:/var/lib/redpanda/data

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERS: redpanda-broker:9092
    depends_on:
      - redpanda-broker

volumes:
  redpanda_data: